/**
 * TodoItem
 *
 * Element of the todo list
 * Pure components with all attributes of a todo coming from react props
 * TodoItem are generated by the TodoList component
 */

import React from "react";

const TodoItem = ({ toggleTodo, completed, text }) => {
  const textdeco = completed
    ? { textDecoration: "line-through" }
    : { textDecoration: "none" };
  return (
    <li style={textdeco} onClick={toggleTodo}>
      {text}
    </li>
  );
};

export default TodoItem;
